//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_MySQL_Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guh
    {
        public int id { get; set; }
        public string Thing1 { get; set; }
        public string Thing2 { get; set; }
    }
}
